config/routes.rb
require 'sidekiq/web'

GitReports::Application.routes.draw do

  root 'pages#home'

  # Pages
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/tutorial', to: 'pages#tutorial', as: 'tutorial'
  get '/about', to: 'pages#about', as: 'about'

  # Authentication routes
  get '/login', to: 'authentications#login', as: 'login'
  get '/github_callback', to: 'authentications#callback'
  get '/logout', to: 'authentications#logout', as: 'logout'
  get '/login_rate_limited', to: 'authentications#login_rate_limited', as: 'login_rate_limited'

  # Repository routes
  scope :issue do
    get ':username/:repositoryname', to: 'repositories#repository', as: 'repository_public', repositoryname: /[^\/]+/
    post ':username/:repositoryname', to: 'repositories#submit', repositoryname: /[^\/]+/
    get ':username/:repositoryname/submitted', to: 'repositories#submitted', as: 'submitted', repositoryname: /[^\/]+/
  end

  resources :repositories, only: [:show, :edit, :update] do
    post 'activate'
    post 'deactivate'
  end

  get '/load_status', to: 'repositories#load_status'

  # Sidekiq monitoring
  constraints -> (r) { r.session[:user_id] && User.where(r.session[:user_id]).count > 0 && User.find(r.session[:user_id]).is_admin } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/views/pages/_repository.html.erb
<tr>
  <td>
    <%= link_to repo.name, repository_path(repo) %>
  </td>
  <td>
    <%= link_to "Edit", edit_repository_path(repo) %>
  </td>
  <td>
    <% if repo.is_active %>
      Active
    <% else %>
      Inactive
    <% end %>
  </td>
  <td>
    <% if repo.is_active %>
      <%= link_to "Deactivate", repository_deactivate_path(repo), method: :post, data: { confirm: "Are you sure you want to deactivate repository '" + repo.name + "'?" } %>
    <% else %>
      <%= link_to "Activate", repository_activate_path(repo), method: :post, data: { confirm: "Are you sure you want to activate repository '" + repo.name + "'?" } %>
    <% end %>
  </td>
  <td>
    <% if repo.is_active %>
      <%= link_to "View", repository_public_path(@current_user.username, repo.name) %>
    <% else %>
      -
    <% end %>
  </td>
</tr>

app/views/pages/about.html.erb
<div class="row">
  <div class="small-12 columns">
    <h3>About Git Reports</h3>
    <p>Git Reports is 100% unaffiliated with GitHub.  It was made as an evening side project by <%= link_to "Zach Schneider", "http://www.schneidmaster.com" %> to fill a personal need.</p>
    <h3>Technologies</h3>
    <p>Git Reports was built with <%= link_to "Rails 4", "https://github.com/rails/rails" %>, <%= link_to "Foundation 5", "foundation.zurb.com" %>, and <%= link_to "MySQL", "http://www.mysql.com/" %>.  It uses the excellent <%= link_to "OctoKit", "https://github.com/octokit/octokit.rb" %> API client to communicate with the GitHub gods.</p>
    <h3>Source</h3>
    <p>Git Reports is open-sourced under the <%= link_to "MIT License", "http://opensource.org/licenses/MIT" %>.  Fittingly enough, the source code is <%= link_to "hosted on GitHub", "https://github.com/schneidmaster/gitreports.com" %>.  You're welcome to clone, tweak, and self-host if you like.  If you add a neat new feature, do me a solid and send me a pull request.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>
      Git Reports
    </h2>
    <hr>
    <h3>
      Intro
    </h3>
    <p>
      Git Reports is a free service that lets you set up a stable URL for anonymous users to submit bugs and other Issues to your GitHub repositories, without exposing your code, requiring users to log in with GitHub, or using a messy <%= link_to "two-repository solution", "https://help.github.com/articles/issues-only-access-permissions" %>.  It works with public and private repositories, and it works with personal and organization repositories.  It's super easy to set up: <%= link_to "log in", login_path%>, allow access, and activate your repository from the list!  Check out the <%= link_to "tutorial", tutorial_path %> for more details.
    </p>
    <hr>
    <h3>
      Pricing
    </h3>
    <p>
      Free and ad-free!
    </p>
    <hr>
    <h3>
      Author
    </h3>
    <p>
      Made with love by <%= link_to "Zach Schneider", "http://www.schneidmaster.com" %>.
    </p>
    <hr>
    <h3>
      What's with the permissions?
    </h3>
    <p>
      The GitHub API doesn't have a whole lot of <%= link_to "scope options", "http://developer.github.com/v3/oauth/#scopes" %>; unfortunately, in order to get write access to a repo's issues, I also have to request write access to the full repo.  The site's open-source, though, so you can <%= link_to "check it out for yourself", "https://github.com/schneidmaster/gitreports.com" %> or even self-host your own copy if that's your thing.
    </p>
    <hr>
    <h3>
      I found a bug/have a feature/etc.!
    </h3>
    <p>
      Dogfood it with a bug report <%= link_to "here", "http://gitreports.com/issue/schneidmaster/gitreports.com" %>, or you can just <%= link_to "create a new issue", "https://github.com/schneidmaster/gitreports.com/issues/new" %> on GitHub; the repo's public.  Feel free to send a pull request if you fix a bug or add a new feature.
    </p>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="row">
  <div class="small-9 columns">
    <h2><%= @current_user.name %></h2>
    <h4><%= link_to @current_user.username, @current_user.github_path %></h4>
  </div>
  <div class="small-3 columns text-right">
    <%= image_tag @current_user.avatar_url, alt: @current_user.name, class: "profile-img" %>
  </div>
</div>
<div id="repo-alert" class="row">
  <div class="small-12 columns">
    <div data-alert class="alert-box warning">
      <span id="repo-load-info">Refreshing repository information from GitHub...</span>
      <a href="#" class="close">&times;</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <hr>
    <% if @current_user.repositories.user_owned.count == 0 %>
      <h3>No Repositories</h3>
      <p>Get to work!</p>
    <% else %>
      <h3>Repositories</h3>
      <table class="responsive">
        <thead>
          <tr>
            <th width="60%">Repository Name</th>
            <th width="10%">Edit</th>
            <th width="10%">Status</th>
            <th width="10%">Toggle</th>
            <th width="10%">Public URL</th>
          </tr>
        </thead>
        <tbody>
          <% @current_user.repositories.user_owned.each do |repo| %>
            <%= render partial: "repository", locals: { repo: repo } %>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <% @current_user.organizations.each do |org| %>
      <hr>
      <h3><%= org.name %></h3>
      <table class="responsive">
        <thead>
          <tr>
            <th width="60%">Repository Name</th>
            <th width="10%">Edit</th>
            <th width="10%">Status</th>
            <th width="10%">Toggle</th>
            <th width="10%">Public URL</th>
          </tr>
        </thead>
        <tbody>
          <% org.repositories.with_user(@current_user).each do |repo| %>
            <%= render partial: "repository", locals: { repo: repo } %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/pages/tutorial.html.erb
<div class="row">
  <div class="small-12 columns">
    <h3>Tutorial</h3>
    <p>
      Let's get you up to speed.
    </p>
    <h5>Log In</h5>
    <p>
      Click the <%= link_to "Login", login_path %> link to connect your GitHub account with Git Reports.  You'll be redirected to log in to GitHub, and then asked if you want to grant the application access to your repositories.  Click "Accept" and you'll be redirected back to the site.
    </p>
    <h5>Profile</h5>
    <p>
      After logging in, you'll be redirected to your <%= link_to "Profile", profile_path %> page.  Here, you'll see a list of repositories that you own.  You'll also see separate tables for any organizations with repositories for which you are a member (only pull access is required).  To see a summary of the repository's information, click its name in the list.  To edit its settings, click the "Edit" link next to the repository's name.  Repositories are always inactive by default; to allow anonymous users to post issues to a repository, activate it by clicking the "Activate" link next to its name.  (The "Activate" link turns into a "Deactivate" link if the repository is already activated, and behaves as you would expect.)  Finally, click the "View" link next to a repository to view its public page if it has been activated- this is where you should direct anonymous users to submit issues/bugs.
    </p>
    <h5>Repository Settings</h5>
    <p>
      Git Reports maintains a few settings for each repository to allow you to customize anonymous user experience and configuration for when the application creates new issues on GitHub.
      <ul>
        <li><b>Display Name:</b> This is the user-friendly name for your repository that will be displayed to anonymous users submitting an issue.  If it's not set, the application will display the repository name by default.</li>
        <li><b>Issue Name:</b> This is the name that will be given to new Git Reports created by the application.  If it's not set, the default is "Git Reports Issue."</li>
        <li><b>Prompt:</b> This is a few sentences of text that will be displayed to anonymous users when they visit the report submission page.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %> in your prompt.  If it's not set, the default is:
        <blockquote>Please enter your bug report or feature request, then click 'Submit'.  If you're reporting a bug, try to include as many details as possible about what you were doing when the bug occurred- a detailed report makes a bug much easier to track down.</blockquote>
        </li>
        <li><b>Followup:</b> This is the result message that will be displayed to a user after they have successfully submitted an issue.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %> in your followup message.  If it's not set, the default is:
        <blockquote>Thanks for submitting your report!  We'll look into it as soon as possible.</blockquote></li>
        <li><b>Labels:</b> This is a comma-separated list of labels that will be applied to new Git Reports created by the application.  Label names must match label options in the issues section of your repository on GitHub; default examples are bug, enhancement, etc.  If this setting isn't set, no labels will be applied to created issues.</li>
        <li><b>Allow Custom Titles:</b> Whether to allow users to set the title of the issue submitted to GitHub. If an Issue Name is set (see above), that will override the custom user title.</li>
      </ul>
    </p>
    <h5>Prefilling Fields</h5>
    <p>
      If you'd like, you can prefill the fields in an active repository's issue page by passing appropriate values as URL parameters. The parameters name, email, and details (e.g. https://gitreports.com/issue/schneidmaster/gitreports.com/?name=The%20Issue) will fill in the respective field with the passed value. Remember to appropriately URL-encode special characters.
    </p>
  </div>
</div>