config/routes.rb
require 'sidekiq/web'

GitReports::Application.routes.draw do

  root 'pages#home'

  # Pages
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/tutorial', to: 'pages#tutorial', as: 'tutorial'
  get '/about', to: 'pages#about', as: 'about'

  # Authentication routes
  get '/login', to: 'authentications#login', as: 'login'
  get '/github_callback', to: 'authentications#callback'
  get '/logout', to: 'authentications#logout', as: 'logout'
  get '/login_rate_limited', to: 'authentications#login_rate_limited', as: 'login_rate_limited'

  # Repository routes
  scope :issue do
    get ':username/:repositoryname', to: 'repositories#repository', as: 'repository_public', repositoryname: /[^\/]+/
    post ':username/:repositoryname', to: 'repositories#submit', repositoryname: /[^\/]+/
    get ':username/:repositoryname/submitted', to: 'repositories#submitted', as: 'submitted', repositoryname: /[^\/]+/
  end

  resources :repositories, only: [:show, :edit, :update] do
    post 'activate'
    post 'deactivate'
  end

  get '/load_status', to: 'repositories#load_status'

  # Sidekiq monitoring
  constraints -> (r) { r.session[:user_id] && User.where(r.session[:user_id]).count > 0 && User.find(r.session[:user_id]).is_admin } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Git Reports is a free service that lets you set up a stable URL for anonymous users to submit bugs and other Issues to your GitHub repositories.">
    <meta name="keywords" content="GitHub, git, issue, report, bug">

    <meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : "Git Reports" %>" />
    <meta property="og:url" content="<%= request.url %>" />
    <meta property="og:site_name" content="Git Reports"/>
    <meta property="og:description" content="Git Reports is a free service that lets you set up a stable URL for anonymous users to submit bugs and other Issues to your GitHub repositories." />
    <meta property="og:image" content="<%= request.protocol + request.host + image_path("alarm.png") %>" />
    <meta property="og:type" content="website" />

    <title><%= content_for?(:title) ? yield(:title) : "Git Reports" %></title>

    <%= favicon_link_tag "favicon.ico" %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!-- Header and Nav -->
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1>
            <%= link_to "Git Reports", root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <!-- Right Nav Section -->
        <ul class="right">
          <% if signed_in? %>
            <li class="divider"></li>
            <li class="has-dropdown">
              <%= link_to current_user.username, profile_path %>
              <ul class="dropdown">
                <li><%= link_to "Profile", profile_path %></li>
                <li><%= link_to "Logout", logout_path %></li>
              </ul>
            </li>
          <% else %>
            <li class="divider"></li>
            <li>
              <%= link_to "Login", login_path %>
            </li>
          <% end %>
        </ul>
      </section>
    </nav>

    <br>

    <% if flash[:error] || flash[:notice] || flash[:success] %>
      <div class="row">
        <div class="small-12 columns">
          <% if flash[:error] -%>
            <div data-alert class="alert-box error">
              <%= h flash[:error] %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
          <% if flash[:notice] -%>
            <div data-alert class="alert-box warning">
              <%= h flash[:notice] %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
          <% if flash[:success] -%>
            <div data-alert class="alert-box success">
              <%= h flash[:success] %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

  <!-- End Header and Nav -->

    <%= yield %>

    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p>Git Reports</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Tutorial", tutorial_path %></li>
              <li><%= link_to "About", about_path %></li>
            </ul>
          </div>
      </div>
    </footer>

    <%= javascript_include_tag "foundation" %>

    <% if ENV['GOOGLE_ANALYTICS_CODE'] %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<%= ENV['GOOGLE_ANALYTICS_CODE'] %>', '<%= request.host %>');
        ga('send', 'pageview');
      </script>
    <% end %>

  </body>
</html>